### ISSUE TITLE
GPL licensing/source question

### ISSUE THREAD

**Issue by SFPROXY** [c3D-Dan/Medusa#1]
First I wanted to say, thank you for being open and sharing your work. Even though I will probably not use this (don't have compatible printer for it or specific need) your work and experience definitely helps the community.

As I was looking on this repo I saw the source files are shared in .step format. While this format is modifiable, and sometimes argued to constitute the source code, it is not always the best option for others to work with.

[According to the GPL](https://www.gnu.org/licenses/gpl-faq.en.html#GPLOtherThanSoftware) the source code is generally understood to be the "preferred form of the work for making changes in it." I'm not sure what CAD software you're using... .step is a great format because it is compatible across different softwares and is not burdened with legal stuff. However, most programs do not use .step as the native format to work in. Fusion 360 uses .f360, openSCAD uses .scad, FreeCAD uses .FCStd. Even if the program or file format is proprietary/non-GPL compliant, sharing the source in that way would be very useful.

In a pinch and for minor modifications, .step is sufficient. But, users and tinkerers miss out on a lot (sketches, construction, other software specific information) Please consider also providing this project's source in whatever file format is native to your software. Thank you!

**Comment by c3D-Dan** [comment]
Hi Grayson,

Thanks for your email.  I'll post inventor files tomorrow.  Thanks for the
tip!

Dan

**Comment by c3D-Dan** [comment]
Files are either too large or too many to be uploaded to github via web browser.  As a stop gap, I've linked the Original Inventor files within their respective folders.

**Comment by c3D-Dan** [comment]
Inventor files added to repo
